apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-app-db-pvc
  namespace: validator  # UPDATE with your namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi  # Postgres data storage
