apiVersion: v1
kind: Service
metadata:
  name: data-app-db
  namespace: validator  # UPDATE with your namespace
  labels:
    app: data-app-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app: data-app-db

---
apiVersion: v1
kind: Service
metadata:
  name: data-app-backend
  namespace: validator  # UPDATE with your namespace
  labels:
    app: data-app-backend
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: http
  selector:
    app: data-app-backend

---
apiVersion: v1
kind: Service
metadata:
  name: data-app-frontend
  namespace: validator  # UPDATE with your namespace
  labels:
    app: data-app-frontend
spec:
  type: ClusterIP
  ports:
    - port: 8091
      targetPort: 8091
      protocol: TCP
      name: http
  selector:
    app: data-app-frontend

